# Generated by Django 4.1 on 2022-10-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Uniquecheck',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
