# Generated by Django 4.1 on 2022-11-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_english_german'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='job_key',
        ),
    ]
