# Generated by Django 4.1 on 2022-11-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_alter_user_cv_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
