# Generated by Django 4.1 on 2022-11-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
