# Generated by Django 4.1 on 2022-11-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_alter_user_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
